blank_issues_enabled: false
contact_links:
  - name: Features, bug reports, questions
    url: https://github.com/glide-browser/glide/discussions/new/choose
    about: The starting point if you have any questions or suggestions about configuration, features or behavior.
