name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - docs
    paths:
      - "src/glide/docs/**"
      - "src/glide/browser/base/content/glide.d.ts"
      - "scripts/build-docs.mts"
      - "scripts/build-api-reference.mts"
      - ".github/workflows/docs.yml"

jobs:
  deploy:
    environment: docs

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global \
            url."https://github.com/mozilla-firefox/firefox.git".insteadOf \
            "git@github.com:mozilla-firefox/firefox.git"

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          cd infra && pnpm --ignore-workspace install --frozen-lockfile

      - name: Bundle vendored dependencies
        run: pnpm bundle

      - name: Compile TS
        run: pnpm build:ts

      - name: Build docs
        run: pnpm build:docs

      - name: Deploy to Cloudflare
        working-directory: infra
        run: |
          pnpm wrangler pages deploy --cwd=../src/glide/docs \
            dist \
            --project-name=glide \
            --branch=main
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
