name: Post release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write # we're pushing a branch

jobs:
  docs:
    name: Update docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          persist-credentials: false

      # will trigger another deploy
      - name: Reset docs branch
        run: |
          git fetch
          git checkout -b docs origin/docs
          git reset --hard origin/main
          git push --force-with-lease
